=== C2DH/statec-exhibit/src/data/schema/dataset.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "id": "population",
            "title": "solde naturel vs solde migratoire per year",
            "timeformat": "YYYY",
            "legend": {
                "v": "solde naturel",
                "v1": "solde migratoire"
            },
            "values": [
                {
                    "t": "1840",
                    "v": 2710,
                    "v1": -20
                }
            ]
        }
    ],
    "required": [
        "id",
        "title",
        "timeformat",
        "legend",
        "values"
    ],
    "additionalProperties": true,
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "population"
            ]
        },
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "solde naturel vs solde migratoire per year"
            ]
        },
        "timeformat": {
            "$id": "#/properties/timeformat",
            "type": "string",
            "title": "The timeformat schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "YYYY"
            ]
        },
        "legend": {
            "$id": "#/properties/legend",
            "type": "object",
            "title": "The legend schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
                {
                    "v": "solde naturel",
                    "v1": "solde migratoire"
                }
            ],
            "required": [
                "v"
            ],
            "additionalProperties": true,
            "properties": {
                "v": {
                    "$id": "#/properties/legend/properties/v",
                    "type": "string",
                    "title": "The v schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "solde naturel"
                    ]
                },
                "v1": {
                    "$id": "#/properties/legend/properties/v1",
                    "type": "string",
                    "title": "The v1 schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "solde migratoire"
                    ]
                }
            }
        },
        "values": {
            "$id": "#/properties/values",
            "type": "array",
            "title": "The values schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    {
                        "t": "1840",
                        "v": 2710,
                        "v1": -20
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "anyOf": [
                    {
                        "$id": "#/properties/values/items/anyOf/0",
                        "type": "object",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": {},
                        "examples": [
                            {
                                "t": "1840",
                                "v": 2710,
                                "v1": -20,
                                "h": "HIGHLIGHT",
                                "label": "counting start officially",
                                "seeAlso": [
                                    "t01m01s01"
                                ]
                            }
                        ],
                        "required": [
                            "t",
                            "v"
                        ],
                        "additionalProperties": true,
                        "properties": {
                            "t": {
                                "$id": "#/properties/values/items/anyOf/0/properties/t",
                                "type": "string",
                                "title": "The t schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "1840"
                                ]
                            },
                            "v": {
                                "$id": "#/properties/values/items/anyOf/0/properties/v",
                                "type": "integer",
                                "title": "The v schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    2710
                                ]
                            },
                            "v1": {
                                "$id": "#/properties/values/items/anyOf/0/properties/v1",
                                "type": "integer",
                                "title": "The v1 schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    -20
                                ]
                            },
                            "h": {
                                "$id": "#/properties/values/items/anyOf/0/properties/h",
                                "type": "string",
                                "title": "The h schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "HIGHLIGHT"
                                ]
                            },
                            "label": {
                                "$id": "#/properties/values/items/anyOf/0/properties/label",
                                "type": "string",
                                "title": "The label schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "counting start officially"
                                ]
                            },
                            "seeAlso": {
                                "$id": "#/properties/values/items/anyOf/0/properties/seeAlso",
                                "type": "array",
                                "title": "The seeAlso schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": [],
                                "examples": [
                                    [
                                        "t01m01s01"
                                    ]
                                ],
                                "additionalItems": true,
                                "items": {
                                    "anyOf": [
                                        {
                                            "$id": "#/properties/values/items/anyOf/0/properties/seeAlso/items/anyOf/0",
                                            "type": "string",
                                            "title": "The first anyOf schema",
                                            "description": "An explanation about the purpose of this instance.",
                                            "default": "",
                                            "examples": [
                                                "t01m01s01"
                                            ]
                                        }
                                    ],
                                    "$id": "#/properties/values/items/anyOf/0/properties/seeAlso/items"
                                }
                            }
                        }
                    }
                ],
                "$id": "#/properties/values/items"
            }
        }
    }
}

=== C2DH/statec-exhibit/src/data/datasets/population.json
{
  "id": "population",
  "title": "population total per year",
  "timeformat": "YYYY",
  "legend": {
    "t": "year",
    "v": "total inhabitants in the Country"
  },
  "values": [
    {
      "t": "1840",
      "v": 170500,
      "h": "HIGHLIGHT",
      "label": "counting start officially",
      "seeAlso": ["t01m01s01"]
    },
    {
      "t": "1841",
      "v": 173190
    },
    {
      "t": "1842",
      "v": 175981
    },
    {
      "t": "1843",
      "v": 177943
    },
    {
      "t": "1844",
      "v": 178207,
      "h": "PEAK",
      "label": "huge increment",
      "seeAlso": ["t01m01s02"]
    },
    {
      "t": "1845",
      "v": 180574
    },
    {
      "t": "1846",
      "v": 183431
    },
    {
      "t": "1847",
      "v": 185023
    },
    {
      "t": "1848",
      "v": 186053
    },
    {
      "t": "1849",
      "v": 186856,
      "h": "WARNING",
      "label": "incomplete data for this year",
      "seeAlso": ["t01m01s03"]
    },
    {
      "t": "1850",
      "v": 189965
    },
    {
      "t": "1851",
      "v": 192488
    },
    {
      "t": "1852",
      "v": 194769
    },
    {
      "t": "1853",
      "v": 193156
    },
    {
      "t": "1854",
      "v": 193117
    },
    {
      "t": "1855",
      "v": 189212
    },
    {
      "t": "1856",
      "v": 189562
    },
    {
      "t": "1857",
      "v": 190379
    },
    {
      "t": "1858",
      "v": 190237
    },
    {
      "t": "1859",
      "v": 191581
    },
    {
      "t": "1860",
      "v": 193822
    },
    {
      "t": "1861",
      "v": 196198
    },
    {
      "t": "1862",
      "v": 197910
    },
    {
      "t": "1863",
      "v": 199733
    },
    {
      "t": "1864",
      "v": 201894
    },
    {
      "t": "1865",
      "v": 203050
    },
    {
      "t": "1866",
      "v": 203697
    },
    {
      "t": "1867",
      "v": 200263
    },
    {
      "t": "1868",
      "v": 196855
    },
    {
      "t": "1869",
      "v": 199991
    },
    {
      "t": "1870",
      "v": 200659
    },
    {
      "t": "1871",
      "v": 202214
    },
    {
      "t": "1872",
      "v": 199994
    },
    {
      "t": "1873",
      "v": 200172
    },
    {
      "t": "1874",
      "v": 201363
    },
    {
      "t": "1875",
      "v": 203679
    },
    {
      "t": "1876",
      "v": 204599
    },
    {
      "t": "1877",
      "v": 206047
    },
    {
      "t": "1878",
      "v": 207439
    },
    {
      "t": "1879",
      "v": 208735
    },
    {
      "t": "1880",
      "v": 209342
    },
    {
      "t": "1881",
      "v": 210589
    },
    {
      "t": "1882",
      "v": 210959
    },
    {
      "t": "1883",
      "v": 212378
    },
    {
      "t": "1884",
      "v": 213464
    },
    {
      "t": "1885",
      "v": 214572
    },
    {
      "t": "1886",
      "v": 214595
    },
    {
      "t": "1887",
      "v": 215764
    },
    {
      "t": "1888",
      "v": 216235
    },
    {
      "t": "1889",
      "v": 215028
    },
    {
      "t": "1890",
      "v": 212834
    },
    {
      "t": "1891",
      "v": 211505
    },
    {
      "t": "1892",
      "v": 212594
    },
    {
      "t": "1893",
      "v": 213275
    },
    {
      "t": "1894",
      "v": 214397
    },
    {
      "t": "1895",
      "v": 216060
    },
    {
      "t": "1896",
      "v": 217910
    },
    {
      "t": "1897",
      "v": 220582
    },
    {
      "t": "1898",
      "v": 223692
    },
    {
      "t": "1899",
      "v": 227205
    },
    {
      "t": "1900",
      "v": 231567
    },
    {
      "t": "1901",
      "v": 234905
    },
    {
      "t": "1902",
      "v": 237219
    },
    {
      "t": "1903",
      "v": 240275
    },
    {
      "t": "1904",
      "v": 242408
    },
    {
      "t": "1905",
      "v": 244631
    },
    {
      "t": "1906",
      "v": 246411
    },
    {
      "t": "1907",
      "v": 249073
    },
    {
      "t": "1908",
      "v": 251709
    },
    {
      "t": "1909",
      "v": 254415
    },
    {
      "t": "1910",
      "v": 256927
    },
    {
      "t": "1911",
      "v": 259211
    },
    {
      "t": "1912",
      "v": 260754
    },
    {
      "t": "1913",
      "v": 263069
    },
    {
      "t": "1914",
      "v": 265495
    },
    {
      "t": "1915",
      "v": 265800
    },
    {
      "t": "1916",
      "v": 264795
    },
    {
      "t": "1917",
      "v": 263487
    },
    {
      "t": "1918",
      "v": 263276
    },
    {
      "t": "1919",
      "v": 262078
    },
    {
      "t": "1920",
      "v": 260969
    },
    {
      "t": "1921",
      "v": 260646
    },
    {
      "t": "1922",
      "v": 261236
    },
    {
      "t": "1923",
      "v": 261792
    },
    {
      "t": "1924",
      "v": 267299
    },
    {
      "t": "1925",
      "v": 272037
    },
    {
      "t": "1926",
      "v": 275675
    },
    {
      "t": "1927",
      "v": 280834
    },
    {
      "t": "1928",
      "v": 284879
    },
    {
      "t": "1929",
      "v": 289666
    },
    {
      "t": "1930",
      "v": 294723
    },
    {
      "t": "1931",
      "v": 299774
    },
    {
      "t": "1932",
      "v": 298827
    },
    {
      "t": "1933",
      "v": 297463
    },
    {
      "t": "1934",
      "v": 297513
    },
    {
      "t": "1935",
      "v": 297243
    },
    {
      "t": "1936",
      "v": 296906
    },
    {
      "t": "1937",
      "v": 298071
    },
    {
      "t": "1938",
      "v": 300730
    },
    {
      "t": "1939",
      "v": 301365
    },
    {
      "t": "1940",
      "v": 298952
    },
    {
      "t": "1941",
      "v": 292991
    },
    {
      "t": "1942",
      "v": 290225
    },
    {
      "t": "1943",
      "v": 289051
    },
    {
      "t": "1944",
      "v": 287891
    },
    {
      "t": "1945",
      "v": 282993
    },
    {
      "t": "1946",
      "v": 284463
    },
    {
      "t": "1947",
      "v": 287151
    },
    {
      "t": "1948",
      "v": 290991
    },
    {
      "t": "1949",
      "v": 292612
    },
    {
      "t": "1950",
      "v": 293822
    },
    {
      "t": "1951",
      "v": 295327
    },
    {
      "t": "1952",
      "v": 296457
    },
    {
      "t": "1953",
      "v": 297965
    },
    {
      "t": "1954",
      "v": 299523
    },
    {
      "t": "1955",
      "v": 301445
    },
    {
      "t": "1956",
      "v": 303586
    },
    {
      "t": "1957",
      "v": 305221
    },
    {
      "t": "1958",
      "v": 307724
    },
    {
      "t": "1959",
      "v": 310361
    },
    {
      "t": "1960",
      "v": 312641
    },
    {
      "t": "1961",
      "v": 314894
    },
    {
      "t": "1962",
      "v": 318796
    },
    {
      "t": "1963",
      "v": 322696
    },
    {
      "t": "1964",
      "v": 325499
    },
    {
      "t": "1965",
      "v": 330001
    },
    {
      "t": "1966",
      "v": 333001
    },
    {
      "t": "1967",
      "v": 334795
    },
    {
      "t": "1968",
      "v": 335233
    },
    {
      "t": "1969",
      "v": 336499
    },
    {
      "t": "1970",
      "v": 338499
    },
    {
      "t": "1971",
      "v": 339796
    },
    {
      "t": "1972",
      "v": 344946
    },
    {
      "t": "1973",
      "v": 348141
    },
    {
      "t": "1974",
      "v": 352639
    },
    {
      "t": "1975",
      "v": 357339
    },
    {
      "t": "1976",
      "v": 360441
    },
    {
      "t": "1977",
      "v": 360889
    },
    {
      "t": "1978",
      "v": 361689
    },
    {
      "t": "1979",
      "v": 362294
    },
    {
      "t": "1980",
      "v": 363447
    },
    {
      "t": "1981",
      "v": 364843
    },
    {
      "t": "1982",
      "v": 365592
    },
    {
      "t": "1983",
      "v": 365439
    },
    {
      "t": "1984",
      "v": 365535
    },
    {
      "t": "1985",
      "v": 366135
    },
    {
      "t": "1986",
      "v": 367182
    },
    {
      "t": "1987",
      "v": 369481
    },
    {
      "t": "1988",
      "v": 371707
    },
    {
      "t": "1989",
      "v": 374870
    },
    {
      "t": "1990",
      "v": 378408
    },
    {
      "t": "1991",
      "v": 383513
    },
    {
      "t": "1992",
      "v": 389600
    },
    {
      "t": "1993",
      "v": 394750
    },
    {
      "t": "1994",
      "v": 400200
    },
    {
      "t": "1995",
      "v": 405650
    },
    {
      "t": "1996",
      "v": 411610
    },
    {
      "t": "1997",
      "v": 416860
    },
    {
      "t": "1998",
      "v": 422060
    },
    {
      "t": "1999",
      "v": 427360
    },
    {
      "t": "2000",
      "v": 433610
    },
    {
      "t": "2001",
      "v": 439010
    },
    {
      "t": "2002",
      "v": 444060
    },
    {
      "t": "2003",
      "v": 448310
    },
    {
      "t": "2004",
      "v": 455010
    },
    {
      "t": "2005",
      "v": 461210
    },
    {
      "t": "2006",
      "v": 469110
    },
    {
      "t": "2007",
      "v": 476210
    },
    {
      "t": "2008",
      "v": 483822
    },
    {
      "t": "2009",
      "v": 493523
    },
    {
      "t": "2010",
      "v": 502089
    },
    {
      "t": "2011",
      "v": 512052
    },
    {
      "t": "2012",
      "v": 524664
    },
    {
      "t": "2013",
      "v": 536850
    },
    {
      "t": "2014",
      "v": 549491
    }
  ]
}

=== C2DH/statec-exhibit/public/datasets/migratory-balance.json
{
  "id": "migratory-balance",
  "title": "Migratory balance per year",
  "timeformat": "YYYY",
  "legend": {
    "v": "Migratory balance"
  },
  "values": [
    {
      "t": "1840", "v": -20
    },
    {
      "t": "1841", "v": -120
    },
    {
      "t": "1842", "v": -150
    },
    {
      "t": "1843", "v": -1700
    },
    {
      "t": "1844", "v": -100
    },
    {
      "t": "1845", "v": -230
    },
    {
      "t": "1846", "v": -910
    },
    {
      "t": "1847", "v": -360
    },
    {
      "t": "1848", "v": -700
    },
    {
      "t": "1849", "v": 340
    },
    {
      "t": "1850", "v": -70
    },
    {
      "t": "1851", "v": -200
    },
    {
      "t": "1852", "v": -3800
    },
    {
      "t": "1853", "v": -1850
    },
    {
      "t": "1854", "v": -5510
    },
    {
      "t": "1855", "v": -1350
    },
    {
      "t": "1856", "v": -1590
    },
    {
      "t": "1857", "v": -2340
    },
    {
      "t": "1858", "v": -460
    },
    {
      "t": "1859", "v": -10
    },
    {
      "t": "1860", "v": -200
    },
    {
      "t": "1861", "v": -640
    },
    {
      "t": "1862", "v": -240
    },
    {
      "t": "1863", "v": -230
    },
    {
      "t": "1864", "v": -400
    },
    {
      "t": "1865", "v": -480
    },
    {
      "t": "1866", "v": -1910
    },
    {
      "t": "1867", "v": -5740
    },
    {
      "t": "1868", "v": -2150
    },
    {
      "t": "1869", "v": -1620
    },
    {
      "t": "1870", "v": -100
    },
    {
      "t": "1871", "v": -2660
    },
    {
      "t": "1872", "v": -1890
    },
    {
      "t": "1873", "v": -1150
    },
    {
      "t": "1874", "v": 120
    },
    {
      "t": "1875", "v": -20
    },
    {
      "t": "1876", "v": -1450
    },
    {
      "t": "1877", "v": -1660
    },
    {
      "t": "1878", "v": -1030
    },
    {
      "t": "1879", "v": -1590
    },
    {
      "t": "1880", "v": -1170
    },
    {
      "t": "1881", "v": -1730
    },
    {
      "t": "1882", "v": -190
    },
    {
      "t": "1883", "v": -930
    },
    {
      "t": "1884", "v": -1180
    },
    {
      "t": "1885", "v": -1940
    },
    {
      "t": "1886", "v": -1270
    },
    {
      "t": "1887", "v": -1900
    },
    {
      "t": "1888", "v": -3040
    },
    {
      "t": "1889", "v": -3830
    },
    {
      "t": "1890", "v": -2630
    },
    {
      "t": "1891", "v": -780
    },
    {
      "t": "1892", "v": -700
    },
    {
      "t": "1893", "v": -700
    },
    {
      "t": "1894", "v": -300
    },
    {
      "t": "1895", "v": -230
    },
    {
      "t": "1896", "v": 850
    },
    {
      "t": "1897", "v": 880
    },
    {
      "t": "1898", "v": 1510
    },
    {
      "t": "1899", "v": 2070
    },
    {
      "t": "1900", "v": 1410
    },
    {
      "t": "1901", "v": -830
    },
    {
      "t": "1902", "v": 100
    },
    {
      "t": "1903", "v": -460
    },
    {
      "t": "1904", "v": -360
    },
    {
      "t": "1905", "v": -800
    },
    {
      "t": "1906", "v": -10
    },
    {
      "t": "1907", "v": -620
    },
    {
      "t": "1908", "v": 0
    },
    {
      "t": "1909", "v": 0
    },
    {
      "t": "1910", "v": -460
    },
    {
      "t": "1911", "v": -680
    },
    {
      "t": "1912", "v": -180
    },
    {
      "t": "1913", "v": -200
    },
    {
      "t": "1914", "v": -2030
    },
    {
      "t": "1915", "v": -2580
    },
    {
      "t": "1916", "v": -2020
    },
    {
      "t": "1917", "v": 0
    },
    {
      "t": "1918", "v": 0,
      "h": "HIGHLIGHT",
      "label": "End of ww2"
    },
    {
      "t": "1919", "v": -1120
    },
    {
      "t": "1920", "v": -2540
    },
    {
      "t": "1921", "v": -1460
    },
    {
      "t": "1922", "v": -1000
    },
    {
      "t": "1923", "v": 3620
    },
    {
      "t": "1924", "v": 2790
    },
    {
      "t": "1925", "v": 1810
    },
    {
      "t": "1926", "v": 3620
    },
    {
      "t": "1927", "v": 2090
    },
    {
      "t": "1928", "v": 2690
    },
    {
      "t": "1929", "v": 3400
    },
    {
      "t": "1930", "v": 2550
    },
    {
      "t": "1931", "v": -2990
    },
    {
      "t": "1932", "v": -2710
    },
    {
      "t": "1933", "v": -1120
    },
    {
      "t": "1934", "v": -1400
    },
    {
      "t": "1935", "v": -1120
    },
    {
      "t": "1936", "v": 80
    },
    {
      "t": "1937", "v": 1700
    },
    {
      "t": "1938", "v": -40
    },
    {
      "t": "1939", "v": -3120
    },
    {
      "t": "1940", "v": -6340
    },
    {
      "t": "1941", "v": -2730
    },
    {
      "t": "1942", "v": -1460
    },
    {
      "t": "1943", "v": -1000
    },
    {
      "t": "1944", "v": -3620
    },
    {
      "t": "1945", "v": 2280
    },
    {
      "t": "1946", "v": 1950
    },
    {
      "t": "1947", "v": 3210
    },
    {
      "t": "1948", "v": 850
    },
    {
      "t": "1949", "v": 860
    },
    {
      "t": "1950", "v": 790
    },
    {
      "t": "1951", "v": 410
    },
    {
      "t": "1952", "v": 530
    },
    {
      "t": "1953", "v": 730
    },
    {
      "t": "1954", "v": 630
    },
    {
      "t": "1955", "v": 930
    },
    {
      "t": "1956", "v": 680
    },
    {
      "t": "1957", "v": 1360
    },
    {
      "t": "1958", "v": 1190
    },
    {
      "t": "1959", "v": 850
    },
    {
      "t": "1960", "v": 950
    },
    {
      "t": "1961", "v": 2400
    },
    {
      "t": "1962", "v": 2800
    },
    {
      "t": "1963", "v": 1620
    },
    {
      "t": "1964", "v": 3130
    },
    {
      "t": "1965", "v": 1760
    },
    {
      "t": "1966", "v": 650
    },
    {
      "t": "1967", "v": -390
    },
    {
      "t": "1968", "v": 660
    },
    {
      "t": "1969", "v": 1690
    },
    {
      "t": "1970", "v": 1040
    },
    {
      "t": "1971", "v": 5090
    },
    {
      "t": "1972", "v": 3230
    },
    {
      "t": "1973", "v": 4890
    },
    {
      "t": "1974", "v": 5090
    },
    {
      "t": "1975", "v": 3490
    },
    {
      "t": "1976", "v": 1040
    },
    {
      "t": "1977", "v": 830
    },
    {
      "t": "1978", "v": 720
    },
    {
      "t": "1979", "v": 1060
    },
    {
      "t": "1980", "v": 1340
    },
    {
      "t": "1981", "v": 440
    },
    {
      "t": "1982", "v": -320
    },
    {
      "t": "1983", "v": 40
    },
    {
      "t": "1984", "v": 480
    },
    {
      "t": "1985", "v": 970
    },
    {
      "t": "1986", "v": 1960
    },
    {
      "t": "1987", "v": 2000
    },
    {
      "t": "1988", "v": 2400
    },
    {
      "t": "1989", "v": 2857
    },
    {
      "t": "1990", "v": 3942
    },
    {
      "t": "1991", "v": 3958
    },
    {
      "t": "1992", "v": 4022
    },
    {
      "t": "1993", "v": 4012
    },
    {
      "t": "1994", "v": 3799
    },
    {
      "t": "1995", "v": 4336
    },
    {
      "t": "1996", "v": 3456
    },
    {
      "t": "1997", "v": 3634
    },
    {
      "t": "1998", "v": 3815
    },
    {
      "t": "1999", "v": 4461
    },
    {
      "t": "2000", "v": 3431
    },
    {
      "t": "2001", "v": 3310
    },
    {
      "t": "2002", "v": 2649
    },
    {
      "t": "2003", "v": 5450
    },
    {
      "t": "2004", "v": 4326
    },
    {
      "t": "2005", "v": 6150
    },
    {
      "t": "2006", "v": 5352
    },
    {
      "t": "2007", "v": 6001
    },
    {
      "t": "2008", "v": 7700
    },
    {
      "t": "2009", "v": 6583
    },
    {
      "t": "2010", "v": 7849
    },
    {
      "t": "2011", "v": 11004
    },
    {
      "t": "2012", "v": 10036
    },
    {
      "t": "2013", "v": 10348
    },
    {
      "t": "2014", "v": 11049
    }
  ]
}

=== C2DH/statec-exhibit/src/data/datasets/density-of-inhabitants.json
{
  "id": "d02-density-of-inhabitants",
  "title": "density of inhabitants",
  "timeformat": "YYYY-MM-dd",
  "legend": {
    "v": "people km2"
  },
  "values": [
    {
      "t": "1839", "tr": "1839-10-01",
      "v": 66,
      "l": "1821-01-01 was 52"
    },
    {
      "t": "1843", "tr": "1843-12-31",
      "v": 69
    },
    {
      "t": "1846", "tr": "1846-12-03",
      "v": 72
    },
    {
      "t": "1847", "tr": "1847-12-31",
      "v": 72
    },
    {
      "t": "1849", "tr": "1849-12-03",
      "v": 73
    },
    {
      "t": "1851", "tr": "1851-12-31",
      "v": 75
    },
    {
      "t": "1855", "tr": "1855-12-03",
      "v": 73
    },
    {
      "t": "1858", "tr": "1858-12-01",
      "v": 74
    },
    {
      "t": "1861", "tr": "1861-12-03",
      "v": 76
    },
    {
      "t": "1864", "tr": "1864-12-03",
      "v": 78
    },
    {
      "t": "1865", "tr": "1865-12-31",
      "v": 79
    },
    {
      "t": "1867", "tr": "1867-12-03",
      "v": 77,
      "h": "HIGHLIGHT",
      "l": "Pandemic?"
    },
    {
      "t": "1871", "tr": "1871-12-01",
      "v": 77
    },
    {
      "t": "1875", "tr": "1875-12-01",
      "v": 79
    },
    {
      "t": "1880", "tr": "1880-12-01",
      "v": 81
    },
    {
      "t": "1885", "tr": "1885-12-01",
      "v": 83
    },
    {
      "t": "1890", "tr": "1890-12-01",
      "v": 82
    },
    {
      "t": "1895", "tr": "1895-12-02",
      "v": 84
    },
    {
      "t": "1900", "tr": "1900-12-01",
      "v": 91
    },
    {
      "t": "1905", "tr": "1905-12-01",
      "v": 95
    },
    {
      "t": "1907", "tr": "1907-06-12",
      "v": 97
    },
    {
      "t": "1910", "tr": "1910-12-01",
      "v": 100
    },
    {
      "t": "1916", "tr": "1916-12-01",
      "v": 102
    },
    {
      "t": "1922", "tr": "1922-12-01",
      "v": 101
    },
    {
      "t": "1927", "tr": "1927-12-01",
      "v": 110
    },
    {
      "t": "1930", "tr": "1930-12-31",
      "v": 116,
      "h": "HIGHLIGHT",
      "l": "+16% in 10 years"
    },
    {
      "t": "1935", "tr": "1935-12-31",
      "v": 115
    },
    {
      "t": "1947", "tr": "1947-12-31",
      "v": 113
    },
    {
      "t": "1960", "tr": "1960-12-31",
      "v": 122
    },
    {
      "t": "1966", "tr": "1966-12-31",
      "v": 129
    },
    {
      "t": "1970", "tr": "1970-12-31",
      "v": 131
    },
    {
      "t": "1981", "tr": "1981-03-31",
      "v": 141
    },
    {
      "t": "1989", "tr": "1989-01-01",
      "v": 145
    }
  ]
}
