=== C2DH/statec-exhibit/src/data/schema/dataset.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "id": "population",
            "title": "solde naturel vs solde migratoire per year",
            "timeformat": "YYYY",
            "legend": {
                "v": "solde naturel",
                "v1": "solde migratoire"
            },
            "values": [
                {
                    "t": "1840",
                    "v": 2710,
                    "v1": -20
                }
            ]
        }
    ],
    "required": [
        "id",
        "title",
        "timeformat",
        "legend",
        "values"
    ],
    "additionalProperties": true,
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "population"
            ]
        },
        "title": {
            "$id": "#/properties/title",
            "type": "string",
            "title": "The title schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "solde naturel vs solde migratoire per year"
            ]
        },
        "timeformat": {
            "$id": "#/properties/timeformat",
            "type": "string",
            "title": "The timeformat schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "YYYY"
            ]
        },
        "legend": {
            "$id": "#/properties/legend",
            "type": "object",
            "title": "The legend schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
                {
                    "v": "solde naturel",
                    "v1": "solde migratoire"
                }
            ],
            "required": [
                "v"
            ],
            "additionalProperties": true,
            "properties": {
                "v": {
                    "$id": "#/properties/legend/properties/v",
                    "type": "string",
                    "title": "The v schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "solde naturel"
                    ]
                },
                "v1": {
                    "$id": "#/properties/legend/properties/v1",
                    "type": "string",
                    "title": "The v1 schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "solde migratoire"
                    ]
                }
            }
        },
        "values": {
            "$id": "#/properties/values",
            "type": "array",
            "title": "The values schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    {
                        "t": "1840",
                        "v": 2710,
                        "v1": -20
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "anyOf": [
                    {
                        "$id": "#/properties/values/items/anyOf/0",
                        "type": "object",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": {},
                        "examples": [
                            {
                                "t": "1840",
                                "v": 2710,
                                "v1": -20,
                                "h": "HIGHLIGHT",
                                "label": "counting start officially",
                                "seeAlso": [
                                    "t01m01s01"
                                ]
                            }
                        ],
                        "required": [
                            "t",
                            "v"
                        ],
                        "additionalProperties": true,
                        "properties": {
                            "t": {
                                "$id": "#/properties/values/items/anyOf/0/properties/t",
                                "type": "string",
                                "title": "The t schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "1840"
                                ]
                            },
                            "v": {
                                "$id": "#/properties/values/items/anyOf/0/properties/v",
                                "type": "integer",
                                "title": "The v schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    2710
                                ]
                            },
                            "v1": {
                                "$id": "#/properties/values/items/anyOf/0/properties/v1",
                                "type": "integer",
                                "title": "The v1 schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    -20
                                ]
                            },
                            "h": {
                                "$id": "#/properties/values/items/anyOf/0/properties/h",
                                "type": "string",
                                "title": "The h schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "HIGHLIGHT"
                                ]
                            },
                            "label": {
                                "$id": "#/properties/values/items/anyOf/0/properties/label",
                                "type": "string",
                                "title": "The label schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "counting start officially"
                                ]
                            },
                            "seeAlso": {
                                "$id": "#/properties/values/items/anyOf/0/properties/seeAlso",
                                "type": "array",
                                "title": "The seeAlso schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": [],
                                "examples": [
                                    [
                                        "t01m01s01"
                                    ]
                                ],
                                "additionalItems": true,
                                "items": {
                                    "anyOf": [
                                        {
                                            "$id": "#/properties/values/items/anyOf/0/properties/seeAlso/items/anyOf/0",
                                            "type": "string",
                                            "title": "The first anyOf schema",
                                            "description": "An explanation about the purpose of this instance.",
                                            "default": "",
                                            "examples": [
                                                "t01m01s01"
                                            ]
                                        }
                                    ],
                                    "$id": "#/properties/values/items/anyOf/0/properties/seeAlso/items"
                                }
                            }
                        }
                    }
                ],
                "$id": "#/properties/values/items"
            }
        }
    }
}

=== C2DH/statec-exhibit/data/datasets/number-of-births.json
{
  "id": "number-of-births",
  "title": "Number of births",
  "timeformat": "YYYY",
  "legend": {
    "v": "newborns"
  },
  "values": [{
      "t": "1841",
      "v": 0
    },
    {
      "t": "1841",
      "v": 6513
    },
    {
      "t": "1842",
      "v": 6533
    },
    {
      "t": "1843",
      "v": 5962
    },
    {
      "t": "1844",
      "v": 6356
    },
    {
      "t": "1845",
      "v": 6669
    },
    {
      "t": "1846",
      "v": 6139
    },
    {
      "t": "1847",
      "v": 5670
    },
    {
      "t": "1848",
      "v": 6256
    },
    {
      "t": "1849",
      "v": 6718
    },
    {
      "t": "1850",
      "v": 6520
    },
    {
      "t": "1851",
      "v": 6788
    },
    {
      "t": "1852",
      "v": 6274
    },
    {
      "t": "1853",
      "v": 6113
    },
    {
      "t": "1854",
      "v": 6231
    },
    {
      "t": "1855",
      "v": 5800
    },
    {
      "t": "1856",
      "v": 6134
    },
    {
      "t": "1857",
      "v": 6145
    },
    {
      "t": "1858",
      "v": 6401
    },
    {
      "t": "1859",
      "v": 6846
    },
    {
      "t": "1860",
      "v": 6594
    },
    {
      "t": "1861",
      "v": 6563
    },
    {
      "t": "1862",
      "v": 6449
    },
    {
      "t": "1863",
      "v": 6824
    },
    {
      "t": "1864",
      "v": 6696
    },
    {
      "t": "1865",
      "v": 6616
    },
    {
      "t": "1866",
      "v": 6459
    },
    {
      "t": "1867",
      "v": 6493
    },
    {
      "t": "1868",
      "v": 6347
    },
    {
      "t": "1869",
      "v": 6467
    },
    {
      "t": "1870",
      "v": 6654
    },
    {
      "t": "1871",
      "v": 6375
    },
    {
      "t": "1872",
      "v": 6380
    },
    {
      "t": "1873",
      "v": 6529
    },
    {
      "t": "1874",
      "v": 6718
    },
    {
      "t": "1875",
      "v": 6330
    },
    {
      "t": "1876",
      "v": 7117
    },
    {
      "t": "1877",
      "v": 6918
    },
    {
      "t": "1878",
      "v": 6720
    },
    {
      "t": "1879",
      "v": 6935
    },
    {
      "t": "1880",
      "v": 6677
    },
    {
      "t": "1881",
      "v": 6744
    },
    {
      "t": "1882",
      "v": 6597
    },
    {
      "t": "1883",
      "v": 6395
    },
    {
      "t": "1884",
      "v": 6595
    },
    {
      "t": "1885",
      "v": 6414
    },
    {
      "t": "1886",
      "v": 6613
    },
    {
      "t": "1887",
      "v": 6435
    },
    {
      "t": "1888",
      "v": 6242
    },
    {
      "t": "1889",
      "v": 6213
    },
    {
      "t": "1890",
      "v": 5980
    },
    {
      "t": "1891",
      "v": 6236
    },
    {
      "t": "1892",
      "v": 5975
    },
    {
      "t": "1893",
      "v": 6239
    },
    {
      "t": "1894",
      "v": 6131
    },
    {
      "t": "1895",
      "v": 6272
    },
    {
      "t": "1896",
      "v": 6281
    },
    {
      "t": "1897",
      "v": 6583
    },
    {
      "t": "1898",
      "v": 6546
    },
    {
      "t": "1899",
      "v": 6967
    },
    {
      "t": "1900",
      "v": 7037
    },
    {
      "t": "1901",
      "v": 7444
    },
    {
      "t": "1902",
      "v": 7416
    },
    {
      "t": "1903",
      "v": 7279
    },
    {
      "t": "1904",
      "v": 7535
    },
    {
      "t": "1905",
      "v": 7431
    },
    {
      "t": "1906",
      "v": 7516
    },
    {
      "t": "1907",
      "v": 7738
    },
    {
      "t": "1908",
      "v": 7639
    },
    {
      "t": "1909",
      "v": 7264
    },
    {
      "t": "1910",
      "v": 7065
    },
    {
      "t": "1911",
      "v": 7126
    },
    {
      "t": "1912",
      "v": 7051
    },
    {
      "t": "1913",
      "v": 7009
    },
    {
      "t": "1914",
      "v": 6781
    },
    {
      "t": "1915",
      "v": 5701
    },
    {
      "t": "1916",
      "v": 4958
    },
    {
      "t": "1917",
      "v": 4516
    },
    {
      "t": "1918",
      "v": 4413
    },
    {
      "t": "1919",
      "v": 4638
    },
    {
      "t": "1920",
      "v": 5621
    },
    {
      "t": "1921",
      "v": 5494
    },
    {
      "t": "1922",
      "v": 5094
    },
    {
      "t": "1923",
      "v": 5468
    },
    {
      "t": "1924",
      "v": 5369
    },
    {
      "t": "1925",
      "v": 5619
    },
    {
      "t": "1926",
      "v": 5639
    },
    {
      "t": "1927",
      "v": 5864
    },
    {
      "t": "1928",
      "v": 6114
    },
    {
      "t": "1929",
      "v": 6210
    },
    {
      "t": "1930",
      "v": 6377
    },
    {
      "t": "1931",
      "v": 5988
    },
    {
      "t": "1932",
      "v": 5295
    },
    {
      "t": "1933",
      "v": 4895
    },
    {
      "t": "1934",
      "v": 4665
    },
    {
      "t": "1935",
      "v": 4523
    },
    {
      "t": "1936",
      "v": 4514
    },
    {
      "t": "1937",
      "v": 4514
    },
    {
      "t": "1938",
      "v": 4486
    },
    {
      "t": "1939",
      "v": 4511
    },
    {
      "t": "1940",
      "v": 3959
    },
    {
      "t": "1941",
      "v": 4029
    },
    {
      "t": "1942",
      "v": 4506
    },
    {
      "t": "1943",
      "v": 4277
    },
    {
      "t": "1944",
      "v": 4128
    },
    {
      "t": "1945",
      "v": 3775
    },
    {
      "t": "1946",
      "v": 4263
    },
    {
      "t": "1947",
      "v": 4178
    },
    {
      "t": "1948",
      "v": 4162
    },
    {
      "t": "1949",
      "v": 4026
    },
    {
      "t": "1950",
      "v": 4116
    },
    {
      "t": "1951",
      "v": 4176
    },
    {
      "t": "1952",
      "v": 4535
    },
    {
      "t": "1953",
      "v": 4565
    },
    {
      "t": "1954",
      "v": 4713
    },
    {
      "t": "1955",
      "v": 4664
    },
    {
      "t": "1956",
      "v": 4833
    },
    {
      "t": "1957",
      "v": 4954
    },
    {
      "t": "1958",
      "v": 4959
    },
    {
      "t": "1959",
      "v": 5037
    },
    {
      "t": "1960",
      "v": 5019
    },
    {
      "t": "1961",
      "v": 5112
    },
    {
      "t": "1962",
      "v": 5137
    },
    {
      "t": "1963",
      "v": 5112
    },
    {
      "t": "1964",
      "v": 5229
    },
    {
      "t": "1965",
      "v": 5297
    },
    {
      "t": "1966",
      "v": 5194
    },
    {
      "t": "1967",
      "v": 4957
    },
    {
      "t": "1968",
      "v": 4704
    },
    {
      "t": "1969",
      "v": 4503
    },
    {
      "t": "1970",
      "v": 4411
    },
    {
      "t": "1971",
      "v": 4443
    },
    {
      "t": "1972",
      "v": 4086
    },
    {
      "t": "1973",
      "v": 3800
    },
    {
      "t": "1974",
      "v": 3925
    },
    {
      "t": "1975",
      "v": 3982
    },
    {
      "t": "1976",
      "v": 3915
    },
    {
      "t": "1977",
      "v": 4053
    },
    {
      "t": "1978",
      "v": 4072
    },
    {
      "t": "1979",
      "v": 4078
    },
    {
      "t": "1980",
      "v": 4169
    },
    {
      "t": "1981",
      "v": 4414
    },
    {
      "t": "1982",
      "v": 4300
    },
    {
      "t": "1983",
      "v": 4185
    },
    {
      "t": "1984",
      "v": 4192
    },
    {
      "t": "1985",
      "v": 4104
    },
    {
      "t": "1986",
      "v": 4309
    },
    {
      "t": "1987",
      "v": 4238
    },
    {
      "t": "1988",
      "v": 4603
    },
    {
      "t": "1989",
      "v": 4665
    },
    {
      "t": "1990",
      "v": 4936
    },
    {
      "t": "1991",
      "v": 4986
    },
    {
      "t": "1992",
      "v": 5149
    },
    {
      "t": "1993",
      "v": 5353
    },
    {
      "t": "1994",
      "v": 5451
    },
    {
      "t": "1995",
      "v": 5421
    },
    {
      "t": "1996",
      "v": 5689
    },
    {
      "t": "1997",
      "v": 5503
    },
    {
      "t": "1998",
      "v": 5386
    },
    {
      "t": "1999",
      "v": 5582
    },
    {
      "t": "2000",
      "v": 5723
    },
    {
      "t": "2001",
      "v": 5459
    },
    {
      "t": "2002",
      "v": 5345
    },
    {
      "t": "2003",
      "v": 5303
    },
    {
      "t": "2004",
      "v": 5452
    },
    {
      "t": "2005",
      "v": 5371
    },
    {
      "t": "2006",
      "v": 5514
    },
    {
      "t": "2007",
      "v": 5477
    },
    {
      "t": "2008",
      "v": 5596
    },
    {
      "t": "2009",
      "v": 5638
    },
    {
      "t": "2010",
      "v": 5874
    },
    {
      "t": "2011",
      "v": 5639
    },
    {
      "t": "2012",
      "v": 6026
    },
    {
      "t": "2013",
      "v": 6115
    },
    {
      "t": "2014",
      "v": 6070
    }
  ]
}

=== C2DH/statec-exhibit/data/datasets/density-of-inhabitants.json
{
  "id": "d02-density-of-inhabitants",
  "title": "density-of-inhabitants",
  "timeformat": "YYYY-MM-dd",
  "legend": {
    "v": "people km2"
  },
  "values": [{
      "t": "1821-01-01",
      "v": 52
    },
    {
      "t": "1839-10-01",
      "v": 66
    },
    {
      "t": "1843-12-31",
      "v": 69
    },
    {
      "t": "1846-12-03",
      "v": 72
    },
    {
      "t": "1847-12-31",
      "v": 72
    },
    {
      "t": "1849-12-03",
      "v": 73
    },
    {
      "t": "1851-12-31",
      "v": 75
    },
    {
      "t": "1855-12-03",
      "v": 73
    },
    {
      "t": "1858-12-01",
      "v": 74
    },
    {
      "t": "1861-12-03",
      "v": 76
    },
    {
      "t": "1864-12-03",
      "v": 78
    },
    {
      "t": "1865-12-31",
      "v": 79
    },
    {
      "t": "1867-12-03",
      "v": 77
    },
    {
      "t": "1871-12-01",
      "v": 77
    },
    {
      "t": "1875-12-01",
      "v": 79
    },
    {
      "t": "1880-12-01",
      "v": 81
    },
    {
      "t": "1885-12-01",
      "v": 83
    },
    {
      "t": "1890-12-01",
      "v": 82
    },
    {
      "t": "1895-12-02",
      "v": 84
    },
    {
      "t": "1900-12-01",
      "v": 91
    },
    {
      "t": "1905-12-01",
      "v": 95
    },
    {
      "t": "1907-06-12",
      "v": 97
    },
    {
      "t": "1910-12-01",
      "v": 100
    },
    {
      "t": "1916-12-01",
      "v": 102
    },
    {
      "t": "1922-12-01",
      "v": 101
    },
    {
      "t": "1927-12-01",
      "v": 110
    },
    {
      "t": "1930-12-31",
      "v": 116
    },
    {
      "t": "1935-12-31",
      "v": 115
    },
    {
      "t": "1947-12-31",
      "v": 113
    },
    {
      "t": "1960-12-31",
      "v": 122
    },
    {
      "t": "1966-12-31",
      "v": 129
    },
    {
      "t": "1970-12-31",
      "v": 131
    },
    {
      "t": "1981-03-31",
      "v": 141
    },
    {
      "t": "1989-01-01",
      "v": 145
    }
  ]
}

=== C2DH/statec-exhibit/public/datasets/trend-excess-arrivals-departures.json
{
  "id": "trend-excess-arrivals-departures",
  "title": "excess of arrivals on departures",
  "timeformat": "YYYY",
  "legend": {
    "v": "people per year"
  },
  "values": [
    {"t": "1960", "v": 2025},
    {"t": "1961", "v": 2943},
    {"t": "1962", "v": 3345},
    {"t": "1963", "v": 1960},
    {"t": "1964", "v": 3960},
    {"t": "1965", "v": 4292},
    {"t": "1966", "v": 3309},
    {"t": "1966", "v":-389, "h": "HIGHLIGHT", "l": "Economic crisis"},
    {"t": "1968", "v": 660},
    {"t": "1969", "v": 1690},
    {"t": "1970", "v": 1091},
    {"t": "1971", "v": 5096},
    {"t": "1972", "v": 3243},
    {"t": "1973", "v": 4892},
    {"t": "1974", "v": 5090},
    {"t": "1975", "v": 3488},
    {"t": "1976", "v": 1054},
    {"t": "1977", "v": 816},
    {"t": "1978", "v": 615},
    {"t": "1979", "v": 1158},
    {"t": "1980", "v": 1359},
    {"t": "1981", "v": 406},
    {"t": "1982",	"v": -306, "h": "HIGHLIGHT", "l": "effect of Recession in the 80s (Oil crisis)"},
    {"t": "1983", "v": 32},
    {"t": "1984", "v": 488},
    {"t": "1985", "v": 824},
    {"t": "1986", "v": 1944},
    {"t": "1987", "v": 2396},
    {"t": "1988", "v": 3069},
    {"t": "1989", "v": 2857},
    {"t": "1990", "v": 3942},
    {"t": "1991", "v": 4173},
    {"t": "1992", "v": 4255},
    {"t": "1993", "v": 4243},
    {"t": "1994", "v": 4004},
    {"t": "1995", "v": 4610},
    {"t": "1996", "v": 3672},
    {"t": "1997", "v": 3832},
    {"t": "1998", "v": 4056},
    {"t": "1999", "v": 4719},
    {"t": "2000", "v": 3644},
    {"t": "2001", "v": 3311},
    {"t": "2002", "v": 2649},
    {"t": "2003", "v": 5412},
    {"t": "2004", "v": 4392},
    {"t": "2005", "v": 6110},
    {"t": "2006", "v": 5351},
    {"t": "2007", "v": 6001},
    {"t": "2008", "v": 7700},
    {"t": "2009", "v": 6583},
    {"t": "2010", "v": 7660}
  ]
}
